In [1]:
import numpy as np
import pandas as pd
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from sklearn import metrics
import time
from imblearn.over_sampling import SMOTE

In [2]:
df = pd.read_csv('data.csv', index_col=0)

In [3]:
y = df.diagnosis
list = ['id', 'diagnosis']
x = df.drop(list, axis=1)
x.head

oversample = SMOTE()
x_n, y_n = oversample.fit_resample(x,y)


In [4]:
data_dia = y_n
data = x_n
data_n_2 = (data - data.mean()) / (data.std())
#data = pd.concat([y, data_n_2], axis=1)

In [5]:
components_set = np.concatenate([np.array([1, 3, 5, 10]), np.arange(50,2050,50)])
kernel_set = np.array(['linear', 'rbf','sigmoid'])

In [12]:
y_n

0      M
1      M
2      M
3      M
4      M
      ..
709    M
710    M
711    M
712    M
713    M
Name: diagnosis, Length: 714, dtype: object

In [13]:
data_n_2

radius   texture  perimeter      area  smoothness  compactness  \
0    0.884913 -2.272919   1.049356  0.767624    1.495576     3.077388   
1    1.587723 -0.467996   1.449071  1.636633   -0.954575    -0.638126   
2    1.348005  0.381954   1.334302  1.307746    0.855013     0.879378   
3   -0.904802  0.169467  -0.740260 -0.876541    3.249843     3.195039   
4    1.511449 -1.305734   1.536138  1.559090    0.178056     0.373295   
..        ...       ...        ...       ...         ...          ...   
709  0.210106  0.831063   0.321195  0.059771    1.567815     1.553427   
710  1.533460  1.318141   1.528592  1.471724    0.126042     1.231986   
711  0.312329  0.651623   0.244559  0.193487   -0.684201    -0.616611   
712 -0.308405  0.503152  -0.205563 -0.387267    0.705836     1.240000   
713  0.331854  0.507696   0.421386  0.205894    1.340552     1.424031   

     concavity  concave_pts  symmetry  fractal_dim  ...  radius_worst  \
0     2.451241     2.273976  2.174450     2.229074  ...      1.595407   
1    -0.191060     0.347329 -0.090671    -0.887043  ...      1.519193   
2     1.178425     1.793128  0.868367    -0.417646  ...      1.241697   
3     1.723740     1.224626  2.838687     4.877207  ...     -0.450638   
4     1.185861     1.202086 -0.101866    -0.581652  ...      1.040415   
..         ...          ...       ...          ...  ...           ...   
709   1.447302     0.901574  0.276583     1.248821  ...     -0.011819   
710   1.375161     1.296453  1.332652    -0.282643  ...      1.465521   
711  -0.527454    -0.296698 -0.796144    -0.811649  ...      0.388982   
712   0.732355     0.287251  0.239910     1.100163  ...     -0.380037   
713   1.113904     1.066932  1.099432     1.483748  ...      0.658451   

     texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0        -1.508927         1.997151    1.671282          1.174534   
1        -0.496846         1.269134    1.569323         -0.510097   
2        -0.143949         1.091363    1.169576          0.393638   
3         0.017518        -0.421952   -0.677512          3.262776   
4        -1.618792         1.082898    0.952709          0.086543   
..             ...              ...         ...               ...   
709       1.285290         0.118121   -0.122764          1.511739   
710       1.289560         1.455025    1.273377         -0.063022   
711       0.936951         0.288828    0.267174         -0.382887   
712       0.453561        -0.162175   -0.433772          1.214962   
713       0.767135         0.559119    0.498069          2.048029   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             2.333935         1.914437              2.064597        2.587807   
1            -0.576747        -0.316647              0.870012       -0.363646   
2             0.868871         0.673892              1.727586        1.012423   
3             3.553505         1.795838              1.945741        5.835841   
4            -0.464938         0.434796              0.516451       -0.979130   
..                 ...              ...                   ...             ...   
709           1.316341         1.424371              1.318210        0.413378   
710           1.458121         1.298962              0.966270        1.340420   
711          -0.647469        -0.509994             -0.244547       -0.089632   
712           1.957221         1.393015              1.429884        0.378226   
713           1.066140         1.400288              1.161930        0.825617   

     fractal_dimension_worst  
0                   1.672532  
1                   0.137956  
2                   0.064001  
3                   4.450998  
4                  -0.490665  
..                       ...  
709                 1.030069  
710                 0.538534  
711                -0.145549  
712                 2.023204  
713                 1.705975  

[714 rows x 30 columns]

In [14]:
for i in range(0, components_set.shape[0]):
    for j in range(0, kernel_set.shape[0]):
        
        components = components_set[i]
        kernel = kernel_set[j]
        print(components,kernel)
        #X = pd.read_csv('X_'+str(components_set[i])+'.csv', index_col = 0)
        startTime = time.time() 
        #X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20)
        X_train, X_test, y_train, y_test = train_test_split(data_n_2, y_n, train_size = 0.7, test_size = 0.3, random_state = 1)
        clf = svm.SVC(kernel = kernel)
        clf.fit(X_train,y_train)
        svm_output = np.zeros(y_train.shape)
        svm_output = clf.predict(X_test)
            
        predicted_output = svm_output
        print(confusion_matrix(y_test, svm_output))
        print(classification_report(y_test, svm_output))
        runTime = time.time() - startTime
        print("T_run:", runTime)

1 linear
[[ 98   2]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.98      0.97       100
           M       0.98      0.97      0.97       115

    accuracy                           0.97       215
   macro avg       0.97      0.97      0.97       215
weighted avg       0.97      0.97      0.97       215

T_run: 0.012862205505371094
1 rbf
[[ 97   3]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.97      0.97       100
           M       0.97      0.97      0.97       115

    accuracy                           0.97       215
   macro avg       0.97      0.97      0.97       215
weighted avg       0.97      0.97      0.97       215

T_run: 0.011834383010864258
1 sigmoid
[[ 97   3]
 [  8 107]]
              precision    recall  f1-score   support

           B       0.92      0.97      0.95       100
           M       0.97      0.93      0.95       115

    accuracy                    

              precision    recall  f1-score   support

           B       0.96      0.97      0.97       100
           M       0.97      0.97      0.97       115

    accuracy                           0.97       215
   macro avg       0.97      0.97      0.97       215
weighted avg       0.97      0.97      0.97       215

T_run: 0.011127948760986328
400 sigmoid
[[ 97   3]
 [  8 107]]
              precision    recall  f1-score   support

           B       0.92      0.97      0.95       100
           M       0.97      0.93      0.95       115

    accuracy                           0.95       215
   macro avg       0.95      0.95      0.95       215
weighted avg       0.95      0.95      0.95       215

T_run: 0.010882139205932617
450 linear
[[ 98   2]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.98      0.97       100
           M       0.98      0.97      0.97       115

    accuracy                           0.97       215
   

              precision    recall  f1-score   support

           B       0.96      0.97      0.97       100
           M       0.97      0.97      0.97       115

    accuracy                           0.97       215
   macro avg       0.97      0.97      0.97       215
weighted avg       0.97      0.97      0.97       215

T_run: 0.011104106903076172
1000 sigmoid
[[ 97   3]
 [  8 107]]
              precision    recall  f1-score   support

           B       0.92      0.97      0.95       100
           M       0.97      0.93      0.95       115

    accuracy                           0.95       215
   macro avg       0.95      0.95      0.95       215
weighted avg       0.95      0.95      0.95       215

T_run: 0.010169267654418945
1050 linear
[[ 98   2]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.98      0.97       100
           M       0.98      0.97      0.97       115

    accuracy                           0.97       215
 

              precision    recall  f1-score   support

           B       0.92      0.97      0.95       100
           M       0.97      0.93      0.95       115

    accuracy                           0.95       215
   macro avg       0.95      0.95      0.95       215
weighted avg       0.95      0.95      0.95       215

T_run: 0.010588407516479492
1600 linear
[[ 98   2]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.98      0.97       100
           M       0.98      0.97      0.97       115

    accuracy                           0.97       215
   macro avg       0.97      0.97      0.97       215
weighted avg       0.97      0.97      0.97       215

T_run: 0.010001897811889648
1600 rbf
[[ 97   3]
 [  4 111]]
              precision    recall  f1-score   support

           B       0.96      0.97      0.97       100
           M       0.97      0.97      0.97       115

    accuracy                           0.97       215
   ma